name: dotnet test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

defaults:
  run:
    working-directory: test/sernickTest

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/sernickTest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Test with the dotnet CLI
      run: dotnet test
      env:
        SkipPerformanceHeavy: true